apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ .Release.Name }}-restarter"
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: "{{ .Release.Name }}-restarter"
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "{{ .Release.Name }}-restarter"
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Release.Name }}-restarter"
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: "{{ .Release.Name }}-restarter"
  apiGroup: rbac.authorization.k8s.io
